name: 构建 NAStool test 镜像  

on:
    workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master

      - 
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v2

      - 
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v2
        
      - 
        name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: s390x.lite.Dockerfile
          platforms: |
            linux/ppc64le
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/nas-tools:ppc64le-test-lite
