name: 构建 NAStool 镜像  

on:
    workflow_dispatch:
    release:
        types: [published]

jobs:
  armv7:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master

      - 
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v2

      - 
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v2
        
      - 
        name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: beta/armv7.beta.Dockerfile
          platforms: |
            linux/arm/v7
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/nas-tools:armv7-beta

  arm64v8:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master

      - 
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v2

      - 
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v2
        
      - 
        name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: beta/arm64v8.beta.Dockerfile
          platforms: |
            linux/arm64/v8
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/nas-tools:arm64v8-beta

  amd64:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master

      - 
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v2

      - 
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v2
        
      - 
        name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: beta/amd64.beta.Dockerfile
          platforms: |
            linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/nas-tools:amd64-beta

  tag:
    needs: [armv7, arm64v8, amd64]
    name: Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: create version tag
        run: |
          docker buildx imagetools create -t ${{ secrets.DOCKER_USERNAME }}/nas-tools:beta \
            ${{ secrets.DOCKER_USERNAME }}/nas-tools:armv7-beta \
            ${{ secrets.DOCKER_USERNAME }}/nas-tools:arm64v8-beta \
            ${{ secrets.DOCKER_USERNAME }}/nas-tools:amd64-beta
