name: 构建 NAStool lite 镜像  

on:
    workflow_dispatch:

jobs:
  armv7:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master

      - 
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v2

      - 
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v2
        
      - 
        name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: armv7.lite.Dockerfile
          platforms: |
            linux/arm/v7
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/nas-tools:armv7-lite

  armv6:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master

      - 
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v2

      - 
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v2
        
      - 
        name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: armv6.lite.Dockerfile
          platforms: |
            linux/arm/v6
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/nas-tools:armv6-lite

  arm64v8:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master

      - 
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v2

      - 
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v2
        
      - 
        name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: arm64v8.lite.Dockerfile
          platforms: |
            linux/arm64/v8
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/nas-tools:arm64v8-lite

  amd64:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master

      - 
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v2

      - 
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v2
        
      - 
        name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: amd64.lite.Dockerfile
          platforms: |
            linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/nas-tools:amd64-lite

  i386:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master

      - 
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v2

      - 
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v2
        
      - 
        name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: 386.lite.Dockerfile
          platforms: |
            linux/386
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/nas-tools:i386-lite

  s390x:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master

      - 
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v2

      - 
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v2
        
      - 
        name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: s390x.lite.Dockerfile
          platforms: |
            linux/s390x
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/nas-tools:s390x-lite

  tag:
    needs: [armv7, armv6, arm64v8, amd64, i386, s390x]
    name: Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: create version tag
        run: |
          docker buildx imagetools create -t ${{ secrets.DOCKER_USERNAME }}/nas-tools:lite \
            ${{ secrets.DOCKER_USERNAME }}/nas-tools:armv7-lite \
            ${{ secrets.DOCKER_USERNAME }}/nas-tools:armv6-lite \
            ${{ secrets.DOCKER_USERNAME }}/nas-tools:arm64v8-lite \
            ${{ secrets.DOCKER_USERNAME }}/nas-tools:amd64-lite \
            ${{ secrets.DOCKER_USERNAME }}/nas-tools:i386-lite \
            ${{ secrets.DOCKER_USERNAME }}/nas-tools:s390x-lite

  tag-version:
    needs: [armv7, armv6, arm64v8, amd64, i386, s390x]
    name: Tag-Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get latest release tag
        id: set-version
        run: |
          echo "::set-output name=version::${GITHUB_REF:10}"

      - name: Set up QEMU
        id: qemu
        if: steps.set-version.outputs.version != ''
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        if: steps.set-version.outputs.version != ''
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Login to DockerHub
        if: steps.set-version.outputs.version != ''
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: create version tag
        if: steps.set-version.outputs.version != ''
        run: |
          docker buildx imagetools create -t ${{ secrets.DOCKER_USERNAME }}/nas-tools:${{ steps.set-version.outputs.version }} \
            ${{ secrets.DOCKER_USERNAME }}/nas-tools:armv7-lite \
            ${{ secrets.DOCKER_USERNAME }}/nas-tools:armv6-lite \
            ${{ secrets.DOCKER_USERNAME }}/nas-tools:arm64v8-lite \
            ${{ secrets.DOCKER_USERNAME }}/nas-tools:amd64-lite \
            ${{ secrets.DOCKER_USERNAME }}/nas-tools:i386-lite \
            ${{ secrets.DOCKER_USERNAME }}/nas-tools:s390x-lite